import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "@/styles/globals.css";
import LeftSidebar from "@/components/NavBar";
import HeaderTool from "@/components/HeaderTool";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Test Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${inter.variable} ${robotoMono.variable}`} lang="en">
      <body className="antialiased">
        <div style={{ display: "flex", minHeight: "80vh" }}>
          <LeftSidebar />
          <div
            style={{
              flex: 1,
              display: "flex",
              flexDirection: "column",
              height: "100vh",
            }}
          >
            <HeaderTool />
            <main style={{ flex: 1, overflow: "auto" }}>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
